"""add company to leads

Revision ID: 4749a8ea474b
Revises: b4399db15af6
Create Date: 2026-08-31 20:40:14.149770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4749a8ea474b'
down_revision: Union[str, Sequence[str], None] = 'b4399db15af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_leads_company_id'), 'leads', ['company_id'], unique=False)
    op.create_foreign_key(None, 'leads', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_company_id'), table_name='leads')
    op.drop_column('leads', 'company_id')
    # ### end Alembic commands ###
