"""link customers to leads

Revision ID: 4b8525ec878a
Revises: 49f663dc5b9e
Create Date: 2026-08-31 21:23:54.755580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b8525ec878a'
down_revision: Union[str, Sequence[str], None] = '49f663dc5b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('lead_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_customers_lead_id'), 'customers', ['lead_id'], unique=True)
    op.create_foreign_key(None, 'customers', 'leads', ['lead_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_lead_id'), table_name='customers')
    op.drop_column('customers', 'lead_id')
    # ### end Alembic commands ###
